/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TWITTER_H_RPCGEN
#define _TWITTER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct tweet {
	char key;
	char usuario[20];
	char topico[20];
	char texto[80];
};
typedef struct tweet tweet;

struct post_tweet_topic {
	char key;
	char topico[80];
	char usuario[20];
	float timestamp;
	char post[80];
};
typedef struct post_tweet_topic post_tweet_topic;

struct user_follow {
	char user[40];
	char user_seguir[40];
};
typedef struct user_follow user_follow;

struct post_users {
	char user[40];
	char topic[40];
	char post[80];
	float timestamp;
};
typedef struct post_users post_users;

#define CREATE_USER_PROG 0x234511F5
#define CREATE_USER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define create_user 5
extern  int * create_user_1(tweet *, CLIENT *);
extern  int * create_user_1_svc(tweet *, struct svc_req *);
extern int create_user_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define create_user 5
extern  int * create_user_1();
extern  int * create_user_1_svc();
extern int create_user_prog_1_freeresult ();
#endif /* K&R C */

#define FOLLOW_USER_PROG 0x234511F6
#define FOLLOW_USER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define follow_user 6
extern  int * follow_user_1(user_follow *, CLIENT *);
extern  int * follow_user_1_svc(user_follow *, struct svc_req *);
extern int follow_user_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define follow_user 6
extern  int * follow_user_1();
extern  int * follow_user_1_svc();
extern int follow_user_prog_1_freeresult ();
#endif /* K&R C */

#define UNFOLLOW_USER_PROG 0x234511F7
#define UNFOLLOW_USER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define unfollow_user 7
extern  int * unfollow_user_1(user_follow *, CLIENT *);
extern  int * unfollow_user_1_svc(user_follow *, struct svc_req *);
extern int unfollow_user_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define unfollow_user 7
extern  int * unfollow_user_1();
extern  int * unfollow_user_1_svc();
extern int unfollow_user_prog_1_freeresult ();
#endif /* K&R C */

#define LIST_USER_PROG 0x234511F8
#define LIST_USER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define list_user 8
extern  int * list_user_1(user_follow *, CLIENT *);
extern  int * list_user_1_svc(user_follow *, struct svc_req *);
extern int list_user_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define list_user 8
extern  int * list_user_1();
extern  int * list_user_1_svc();
extern int list_user_prog_1_freeresult ();
#endif /* K&R C */

#define CREATE_TOPIC_PROG 0x234511F9
#define CREATE_TOPIC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define create_topic 9
extern  int * create_topic_1(post_tweet_topic *, CLIENT *);
extern  int * create_topic_1_svc(post_tweet_topic *, struct svc_req *);
extern int create_topic_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define create_topic 9
extern  int * create_topic_1();
extern  int * create_topic_1_svc();
extern int create_topic_prog_1_freeresult ();
#endif /* K&R C */

#define POST_TOPIC_PROG 0x234511FA
#define POST_TOPIC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define post_topic 10
extern  post_users * post_topic_1(post_tweet_topic *, CLIENT *);
extern  post_users * post_topic_1_svc(post_tweet_topic *, struct svc_req *);
extern int post_topic_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define post_topic 10
extern  post_users * post_topic_1();
extern  post_users * post_topic_1_svc();
extern int post_topic_prog_1_freeresult ();
#endif /* K&R C */

#define POST_TWEET_PROG 0x234511FB
#define POST_TWEET_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define post_tweet 11
extern  post_users * post_tweet_1(post_tweet_topic *, CLIENT *);
extern  post_users * post_tweet_1_svc(post_tweet_topic *, struct svc_req *);
extern int post_tweet_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define post_tweet 11
extern  post_users * post_tweet_1();
extern  post_users * post_tweet_1_svc();
extern int post_tweet_prog_1_freeresult ();
#endif /* K&R C */

#define LIST_TOPIC_PROG 0x234511FC
#define LIST_TOPIC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define list_topic 12
extern  int * list_topic_1(user_follow *, CLIENT *);
extern  int * list_topic_1_svc(user_follow *, struct svc_req *);
extern int list_topic_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define list_topic 12
extern  int * list_topic_1();
extern  int * list_topic_1_svc();
extern int list_topic_prog_1_freeresult ();
#endif /* K&R C */

#define RETRIEVE_TOPIC_PROG 0x234511FD
#define RETRIEVE_TOPIC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define retrieve_topic 13
extern  post_users * retrieve_topic_1(post_tweet_topic *, CLIENT *);
extern  post_users * retrieve_topic_1_svc(post_tweet_topic *, struct svc_req *);
extern int retrieve_topic_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define retrieve_topic 13
extern  post_users * retrieve_topic_1();
extern  post_users * retrieve_topic_1_svc();
extern int retrieve_topic_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_tweet (XDR *, tweet*);
extern  bool_t xdr_post_tweet_topic (XDR *, post_tweet_topic*);
extern  bool_t xdr_user_follow (XDR *, user_follow*);
extern  bool_t xdr_post_users (XDR *, post_users*);

#else /* K&R C */
extern bool_t xdr_tweet ();
extern bool_t xdr_post_tweet_topic ();
extern bool_t xdr_user_follow ();
extern bool_t xdr_post_users ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TWITTER_H_RPCGEN */
