/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "twitter.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
create_user_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		tweet create_user_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case create_user:
		_xdr_argument = (xdrproc_t) xdr_tweet;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) create_user_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
follow_user_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		user_follow follow_user_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case follow_user:
		_xdr_argument = (xdrproc_t) xdr_user_follow;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) follow_user_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
unfollow_user_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		user_follow unfollow_user_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case unfollow_user:
		_xdr_argument = (xdrproc_t) xdr_user_follow;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) unfollow_user_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
list_user_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		user_follow list_user_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case list_user:
		_xdr_argument = (xdrproc_t) xdr_user_follow;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) list_user_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
create_topic_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		post_tweet_topic create_topic_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case create_topic:
		_xdr_argument = (xdrproc_t) xdr_post_tweet_topic;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) create_topic_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
post_topic_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		post_tweet_topic post_topic_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case post_topic:
		_xdr_argument = (xdrproc_t) xdr_post_tweet_topic;
		_xdr_result = (xdrproc_t) xdr_post_users;
		local = (char *(*)(char *, struct svc_req *)) post_topic_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
post_tweet_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		post_tweet_topic post_tweet_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case post_tweet:
		_xdr_argument = (xdrproc_t) xdr_post_tweet_topic;
		_xdr_result = (xdrproc_t) xdr_post_users;
		local = (char *(*)(char *, struct svc_req *)) post_tweet_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
list_topic_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		user_follow list_topic_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case list_topic:
		_xdr_argument = (xdrproc_t) xdr_user_follow;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) list_topic_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
retrieve_topic_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		post_tweet_topic retrieve_topic_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case retrieve_topic:
		_xdr_argument = (xdrproc_t) xdr_post_tweet_topic;
		_xdr_result = (xdrproc_t) xdr_post_users;
		local = (char *(*)(char *, struct svc_req *)) retrieve_topic_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CREATE_USER_PROG, CREATE_USER_VERS);
	pmap_unset (FOLLOW_USER_PROG, FOLLOW_USER_VERS);
	pmap_unset (UNFOLLOW_USER_PROG, UNFOLLOW_USER_VERS);
	pmap_unset (LIST_USER_PROG, LIST_USER_VERS);
	pmap_unset (CREATE_TOPIC_PROG, CREATE_TOPIC_VERS);
	pmap_unset (POST_TOPIC_PROG, POST_TOPIC_VERS);
	pmap_unset (POST_TWEET_PROG, POST_TWEET_VERS);
	pmap_unset (LIST_TOPIC_PROG, LIST_TOPIC_VERS);
	pmap_unset (RETRIEVE_TOPIC_PROG, RETRIEVE_TOPIC_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CREATE_USER_PROG, CREATE_USER_VERS, create_user_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CREATE_USER_PROG, CREATE_USER_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, FOLLOW_USER_PROG, FOLLOW_USER_VERS, follow_user_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (FOLLOW_USER_PROG, FOLLOW_USER_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, UNFOLLOW_USER_PROG, UNFOLLOW_USER_VERS, unfollow_user_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (UNFOLLOW_USER_PROG, UNFOLLOW_USER_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, LIST_USER_PROG, LIST_USER_VERS, list_user_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (LIST_USER_PROG, LIST_USER_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, CREATE_TOPIC_PROG, CREATE_TOPIC_VERS, create_topic_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CREATE_TOPIC_PROG, CREATE_TOPIC_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, POST_TOPIC_PROG, POST_TOPIC_VERS, post_topic_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (POST_TOPIC_PROG, POST_TOPIC_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, POST_TWEET_PROG, POST_TWEET_VERS, post_tweet_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (POST_TWEET_PROG, POST_TWEET_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, LIST_TOPIC_PROG, LIST_TOPIC_VERS, list_topic_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (LIST_TOPIC_PROG, LIST_TOPIC_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, RETRIEVE_TOPIC_PROG, RETRIEVE_TOPIC_VERS, retrieve_topic_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RETRIEVE_TOPIC_PROG, RETRIEVE_TOPIC_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CREATE_USER_PROG, CREATE_USER_VERS, create_user_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CREATE_USER_PROG, CREATE_USER_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, FOLLOW_USER_PROG, FOLLOW_USER_VERS, follow_user_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (FOLLOW_USER_PROG, FOLLOW_USER_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, UNFOLLOW_USER_PROG, UNFOLLOW_USER_VERS, unfollow_user_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (UNFOLLOW_USER_PROG, UNFOLLOW_USER_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, LIST_USER_PROG, LIST_USER_VERS, list_user_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (LIST_USER_PROG, LIST_USER_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CREATE_TOPIC_PROG, CREATE_TOPIC_VERS, create_topic_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CREATE_TOPIC_PROG, CREATE_TOPIC_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, POST_TOPIC_PROG, POST_TOPIC_VERS, post_topic_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (POST_TOPIC_PROG, POST_TOPIC_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, POST_TWEET_PROG, POST_TWEET_VERS, post_tweet_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (POST_TWEET_PROG, POST_TWEET_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, LIST_TOPIC_PROG, LIST_TOPIC_VERS, list_topic_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (LIST_TOPIC_PROG, LIST_TOPIC_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, RETRIEVE_TOPIC_PROG, RETRIEVE_TOPIC_VERS, retrieve_topic_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RETRIEVE_TOPIC_PROG, RETRIEVE_TOPIC_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
