/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "twitter.h"

bool_t
xdr_tweet (XDR *xdrs, tweet *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_char (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->usuario, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->topico, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->texto, 80,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_post_tweet_topic (XDR *xdrs, post_tweet_topic *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_char (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->topico, 80,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->usuario, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->timestamp))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->post, 80,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user_follow (XDR *xdrs, user_follow *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->user, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->user_seguir, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_post_users (XDR *xdrs, post_users *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->user, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->topic, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->post, 80,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->timestamp))
		 return FALSE;
	return TRUE;
}
